### ISSUE TITLE
Where is mobc-postgres?

### ISSUE THREAD

**Issue by ohmyarch** [importcjj/mobc#18]
Now mobc v0.4.0 is out, I try to find a new version for mobc-postgres, but.. looks like its code was removed😂.
In addition: tokio-postgres v0.5.1 is out.

**Comment by importcjj** [comment]
Sorry about that, I will publish a new version of mobs-Postgres in few days. Or you can just use the code in the examples folder.

**Comment by importcjj** [comment]
@ohmyarch I just published a new version.
https://crates.io/crates/mobc-postgres
