### ISSUE TITLE
Is it possible to determine whether a connection is newly established?

### ISSUE THREAD

**Issue by ohmyarch** [importcjj/mobc#19]
I mean, when calling Pool::get().

**Comment by importcjj** [comment]
I can't understand your question. Can you give me more information? For example, what do you want to do with this feature?

**Comment by ohmyarch** [comment]
For example, for newly established connections, execute some queries, and for connections that already exist in the connection pool, there is no need to do those preparations, which may improve performance.

**Comment by importcjj** [comment]
Do you mean like this? 
```rust
let conn = Pool.get().await?;
if conn.is_brand_new() {
    // Execute some queries
}
```

**Comment by ohmyarch** [comment]
Yes! That's it.

**Comment by importcjj** [comment]
@ohmyarch You can update mobc to latest 0.5.3.
