### ISSUE TITLE
Now, the way to use Redis async connection is ugly

### ISSUE THREAD

**Issue by importcjj** [importcjj/mobc#2]
The async API is coming.
see https://github.com/mitsuhiko/redis-rs/pull/232

**Comment by RuralDependencies** [comment]
Hi,

Is this code still applicable for the connection pool? Or is it gonna massively change in the next few days?

Me and my company is going to use Redis and we want to re-use the same connection from multiple threads, what is currently the best way?

Thanks for the help! :)

**Comment by importcjj** [comment]
Re-using connections in multi threads, you can try the r2d2. mobc is just like r2d2, but it supports the async/await syntax and driven by tokio runtime. mobc-redis pool works good now，a new break version for it will also be released when the redis-rs maintainer has published the new async api.

**Comment by RuralDependencies** [comment]
Thank you, quick question, do you use Telegram? I'd like to ask you a few questions about a potential remote work opportunity.

Can you email me merkelo@nym.hush.com
