### ISSUE TITLE
Support AsyncRead/AsyncWrite?

### ISSUE THREAD

**Issue by zkat** [importcjj/mobc#39]
Hey hey.

I'm trying to use mobc to pool `TcpStream`, and I notice that the wrapper `Connection` doesn't implement `AsyncRead` or `AsyncWrite`, which means the connection can't be passed around to some contexts where those traits are required. Are there any plans to support a connection (or connection variant?) that supports these?

**Comment by importcjj** [comment]
Maybe you can get the mutation reference of a tcp stream with the `DerefMut` trait.
