### ISSUE TITLE
TLS/SSL support for Redis

### ISSUE THREAD

**Issue by jasonpkovalski** [importcjj/mobc#43]
The 0.17 version of the `redis` crate contains TLS/SSL support.  I'm currently using a forked version of this repo, and I have opened a PR for this: https://github.com/importcjj/mobc/pull/42.

**Comment by importcjj** [comment]
Sorry for late. I had published a new version of `mobc-redis`.

**Comment by Snazzie** [comment]
How do we actually enable tls feature. `can't connect with TLS, the feature is not enabled- InvalidClientConfig`
