### ISSUE TITLE
Upgrade to Tokio 0.3

### ISSUE THREAD

**Issue by zupzup** [importcjj/mobc#44]
With [Tokio 0.3](https://tokio.rs/blog/2020-10-tokio-0-3) out, it would be nice to update, especially since this is supposed to be the last version before 1.0

There is already an updated version of [tokio-postgres](https://github.com/sfackler/rust-postgres/blob/master/tokio-postgres/CHANGELOG.md)

For redis, there is an [issue](https://github.com/mitsuhiko/redis-rs/issues/396) to upgrade as well.

**Comment by importcjj** [comment]
Sorry for late. I just published `0.6.0` for `mobc` and `mobc-postgres`.  
If you are still using mobc, feedbacks is welcomed, and I will fix them as soon as possible.

**Comment by zupzup** [comment]
That's fantastic, thank you so much!
