### ISSUE TITLE
Wrong database configuration returns Timeout

### ISSUE THREAD

**Issue by pimeys** [importcjj/mobc#5]
If you connect to postgres by creating a new `Pool`, and the connection configuration has a non-existing database, mobc will wait a while and then throw `Error::Timeout`. Would be nicer if we'd get the exact reason why the connection failed and it would happen immediately instead of waiting until the timeout.

**Comment by importcjj** [comment]
Thanks for the feedback, I will fix it.

**Comment by importcjj** [comment]
v0.2.9 released

**Comment by pimeys** [comment]
Nice! Now it just works for us and is one crate less depending on tokio only. Thank you!

https://github.com/prisma/quaint

**Comment by importcjj** [comment]
Good, welcome to feedback if you have any questions
