### ISSUE TITLE
Possible pool depletion and elevated number of timeouts

### ISSUE THREAD

**Issue by Sytten** [importcjj/mobc#52]
I am very green on rust so please be indulgent, but I am investigating a pool depletion bug (see https://github.com/prisma/prisma/issues/5977) from Prisma (which uses mobc under a lot of layers).

## Investigation 1: conn_requests storage
Now if I understand correctly if the pool is above the limit, the request is added to `conn_requests` (https://github.com/importcjj/mobc/blob/master/src/lib.rs#L546).
This is a HashMap, which I think should be replaced by a FIFO queue since the way it is queried (https://github.com/importcjj/mobc/blob/master/src/lib.rs#L661) means that a "random" request can be served (aka not necessarily the oldest). 

Imagine a scenario with a pool of 1 and a get timeout of 5s, request A comes in at 0s and takes 5s to complete. Request B comes in at 2s and waits. Request C comes in at 3s and waits. A finishes, by random luck C gets the connection and takes 3s to complete. Request B will timeout where it should have not. In a real system with a legit backlog, this means a request could wait for a connection for a long time.

## Investigation 2: put_conn
So once the connection goes out of scope, the `Drop` trait makes sure that the connection is returned to the pool. This is assumed by the `put_conn` (https://github.com/importcjj/mobc/blob/master/src/lib.rs#L637) function. This function then tries to give the connection back to a request that is waiting for one. Now I believe a loop is missing here: https://github.com/importcjj/mobc/blob/master/src/lib.rs#L660-L673

Again, imagine a scenario with a pool of 1 and a get timeout of 5s, request A comes in at 0s and takes 10s to complete. Request B comes in at 2s and waits. Request C comes in at 8s and waits. A finishes, B is selected to get the connection but the request has been cancelled so the connection is just returned to the pool directly (https://github.com/importcjj/mobc/blob/master/src/lib.rs#L665). C is never served and timeout after 5s.

**Comment by importcjj** [comment]
Thanks for your contribution. I published a new version with your optimizing code merged.
