### ISSUE TITLE
Incompatible with latest stable actix-web

### ISSUE THREAD

**Issue by TheCGDF** [importcjj/mobc#59]
https://github.com/importcjj/mobc/blob/master/examples/actix-web.rs

This example can be built but cannot be run with latest stable actix-web.

**Comment by importcjj** [comment]
Do you mean the actix-web 3?

**Comment by TheCGDF** [comment]
Yes. And it should be written like this:
```
#[actix_web::main]
async fn main() -> std::io::Result<()> {
    actix_rt::System::with_tokio_rt(|| {
        tokio::runtime::Builder::new_multi_thread()
            .enable_all()
            .build()
            .unwrap()
    })
        .block_on(async {
            let config = tokio_postgres::Config::from_str("postgres://...").unwrap();
            let manager = mobc_postgres::PgConnectionManager::new(config, tokio_postgres::NoTls);
            let pool = mobc::Pool::builder().max_open(2u64).build(manager);
            actix_web::HttpServer::new(move ||
                actix_web::App::new()
                    .data(pool.clone())
                    .service(login)
                    )
            )
                .bind("127.0.0.1:8080")?
                .run()
                .await
        })
}
```
https://github.com/actix/actix-web/issues/1283

**Comment by importcjj** [comment]
I tried this code, but it still failed.  I found that `actix-web v3` depends on `actix-rt v1`,  and `actix-rt v1` depends on `tokio v0.2`,
but `mobc v0.7` spawns tasks uses `tokio v1` by default, so it's not compatible with `actix-web v3`.

**Comment by TheCGDF** [comment]
I think it should work because I'm actually using this code.
`actix-rt = "2.2.0"` will provide `tokio v1` for `mobc`.
