### ISSUE TITLE
Switch to tokio 0.2

### ISSUE THREAD

**Issue by importcjj** [importcjj/mobc#7]
Switch to tokio 0.2

**Comment by pimeys** [comment]
I tried to look through how to implement this and the loss of tokio's `DefaultExecutor` makes it really tricky to update mobc...

**Comment by importcjj** [comment]
Yes, some of tokio's APIs have changed, but I'll try to fix them.
If all goes well, it should be finished in a few days.

**Comment by pimeys** [comment]
Yeah. There is no `DefaultExecutor` anymore. What I tried is to use a `Handle` from the `Runtime`. But you must pass this explicitely. No more global executor.

**Comment by importcjj** [comment]
0.3.0 released
