### ISSUE TITLE
Metrics related to opened connections are registered incorrectly

### ISSUE THREAD

**Issue by alencardc** [importcjj/mobc#73]
### Description

The `mobc_pool_connections_opened_total` and `mobc_pool_connections_open` metrics are not handled according to their descriptions. As described in the [source code](https://github.com/importcjj/mobc/blob/main/src/metrics_utils.rs), `mobc_pool_connections_opened_total` (a counter) refers to the total number of pool connections opened, and `mobc_pool_connections_open` (a gauge) refers to the current number of opened connections. However, `mobc_pool_connections_opened_total` values are emitted as a gauge, and `mobc_pool_connections_open` values are emitted both as gauge and counter. Also, the `mobc_pool_connections_open` gauge value is equal to the opposite of `mobc_pool_connections_closed_total`, and the `mobc_pool_connections_open` counter value is equal to `mobc_pool_connections_opened_total`.

### How to reproduce

Build a new pool, set a metrics recorder, and observe how the desired metrics are registered, incremented, and decremented.

<details>
<summary>Simple example to reproduce</summary>

It basically extends the `tide.rs` example provided in this repo by adding a `LogRecorder` responsible for logging every metric change that is emitted. 

Observe how the `mobc_pool_connections_opened_total` is incremented as a gauge instead of a counter, and all `mobc_pool_connections_open` increments are made as a counter, but all decrements are made as a gauge.

```rust
mod foodb;
use foodb::FooManager;
use metrics::{
    Counter, CounterFn, Gauge, GaugeFn, Histogram, HistogramFn, Key, KeyName, Recorder,
    SetRecorderError, Unit,
};

use std::{sync::Arc, time::Duration};
use tide::Request;

// Defines log handlers for each metric operation
pub(crate) struct MetricHandle(Key);

impl CounterFn for MetricHandle {
    fn increment(&self, value: u64) {
        log::debug!("counter increment {} -> {}", self.0.name(), value);
    }

    fn absolute(&self, value: u64) {
        log::debug!("counter absolute {} -> {}", self.0.name(), value);
    }
}

impl GaugeFn for MetricHandle {
    fn increment(&self, value: f64) {
        log::debug!("gauge increment {} -> {}", self.0.name(), value);
    }

    fn decrement(&self, value: f64) {
        log::debug!("gauge decrement {} -> {}", self.0.name(), value);
    }

    fn set(&self, value: f64) {
        log::debug!("gauge set {} -> {}", self.0.name(), value);
    }
}

impl HistogramFn for MetricHandle {
    fn record(&self, value: f64) {
        log::debug!("histogram record {} -> {}", self.0.name(), value);
    }
}

// Defines a simple Metrics Recorder that logs all metrics changes
struct LogRecorder;

impl Recorder for LogRecorder {
    fn describe_counter(&self, key_name: KeyName, _unit: Option<Unit>, description: &'static str) {
        log::debug!("counter '{}' -> {}", key_name.as_str(), description);
    }

    fn describe_gauge(&self, key_name: KeyName, _unit: Option<Unit>, description: &'static str) {
        log::debug!("gauge '{}' -> {}", key_name.as_str(), description);
    }

    fn describe_histogram(
        &self,
        key_name: KeyName,
        _unit: Option<Unit>,
        description: &'static str,
    ) {
        log::debug!("histogram '{}' -> {}", key_name.as_str(), description);
    }

    fn register_counter(&self, key: &Key) -> Counter {
        Counter::from_arc(Arc::new(MetricHandle(key.clone())))
    }

    fn register_gauge(&self, key: &Key) -> Gauge {
        Gauge::from_arc(Arc::new(MetricHandle(key.clone())))
    }

    fn register_histogram(&self, key: &Key) -> Histogram {
        Histogram::from_arc(Arc::new(MetricHandle(key.clone())))
    }
}

static RECORDER: LogRecorder = LogRecorder;
pub fn set_recorder() -> Result<(), SetRecorderError> {
    metrics::set_recorder(&RECORDER)
}


// Example setup
type Pool = mobc::Pool<FooManager>;

async fn ping(req: Request<Pool>) -> tide::Result {
    let pool = req.state();
    let conn = pool.get().await.unwrap();
    Ok(conn.query().await.into())
}

#[async_std::main]
async fn main() {
    env_logger::init();
    set_recorder().unwrap();

    let manager = FooManager;
    let pool = Pool::builder()
        .max_open(12)
        .max_idle_lifetime(Some(Duration::from_secs(3)))
        .build(manager);

    let mut app = tide::with_state(pool);
    app.at("/").get(ping);
    app.listen("127.0.0.1:7777").await.unwrap();
}

```

</details>

### Expected behavior

* `mobc_pool_connections_opened_total` to be incremented as a counter.
* `mobc_pool_connections_open` to be incremented and decremented as a gauge.

### Notes

* [PR #69](https://github.com/importcjj/mobc/pull/69) added metrics to mobc.
* This behavior was reported by [Prisma ORM](https://www.prisma.io/) users on issues [#18760](https://github.com/prisma/prisma/issues/18760) and [#18761](https://github.com/prisma/prisma/issues/18761).
* Prisma uses the mobc emitted metrics to expose part of its metrics. The mapping applied to rename mobc metrics can be found [here](https://github.com/prisma/prisma-engines/blob/main/query-engine/metrics/src/lib.rs#L88), and the related doc [here](https://www.prisma.io/docs/concepts/components/prisma-client/metrics).

**Comment by garrensmith** [comment]
@alencardc and @miguelff I've pushed 0.8.2 to crates with this fix.
