### ISSUE TITLE
Please release new version of `mobc-redis`

### ISSUE THREAD

**Issue by dcormier** [importcjj/mobc#80]
The latest published version of `mobc-redis` is `0.8.0`, but this repo has ~~`0.8.2`~~ `0.8.3`, which includes use of an updated version of the `redis` crate.

It would be helpful if that were released.

**Comment by julien-leclercq** [comment]
any news regarding this ?

**Comment by garrensmith** [comment]
I've bumped the version up to `0.8.2.` for mobc-redis. But the `cargo.toml` is configured to use `0.8` of mobc so it will always use the latest:

```
mobc-redis v0.8.2 (/Users/garren/dev/mobc/mobc-redis)
    ── mobc v0.8.3 (/Users/garren/dev/mobc)
```
