### ISSUE TITLE
Debug for Pool struct

### ISSUE THREAD

**Issue by pjb157** [importcjj/mobc#83]
Hi all,

I am currently working on a project using this crate which is awesome and has helped me loads. I am having trouble fitting it into my webserver as I need the Pool struct to implement Debug functionality. Would it be possible to add into this crate?

Thanks for any help!

**Comment by garrensmith** [comment]
@pjb157 what are you looking to do? 
Could you create a PR that implements the debug functionality and then we can see what impact that has.

**Comment by pjb157** [comment]
Yeah sure I've opened up https://github.com/importcjj/mobc/pull/84 which the structs I need debug impl on. I am not really too bothered about the output of the debug just that it exists so it doesn't break my other work. Happy for you to suggest a better impl of debug but just kept it basic.

**Comment by garrensmith** [comment]
This is merged in in #84

**Comment by pjb157** [comment]
Awesome thanks do you have an idea of a timeline when the crate will be next released?

**Comment by garrensmith** [comment]
I'll try and do a new release this week but you can pull from github using cargo
