### ISSUE TITLE
cargo build: Failed to select a version for `mobc-postgres`

### ISSUE THREAD

**Issue by ohmyarch** [importcjj/mobc#9]
the package `xxx` depends on `mobc-postgres`, with features: `tokio` but `mobc-postgres` does not have these features.

mobc-postgres version: 0.3.0

**Comment by ohmyarch** [comment]
Also tried git version, same.

**Comment by importcjj** [comment]
@ohmyarch  What's your `tokio' version?

**Comment by ohmyarch** [comment]
tokio = { version = "0.2.2", features = ["tcp", "sync", "time", "stream", "macros", "rt-threaded"] }

**Comment by importcjj** [comment]
Thanks for the feedback. 

I found out the cause.

https://github.com/importcjj/mobc/blob/0.3.0/postgres/Cargo.toml#L15

`tokio` is not in the dependencies of `mobc-postgres`,  but I try to enable the feature `tokio/rt-threaded`.

I fixed the bug on the master branch, and a new version will be released soon.

**Comment by importcjj** [comment]
@ohmyarch Try mobc-postgres `0.3.1`

**Comment by ohmyarch** [comment]
It works.🎉
