### ISSUE TITLE
Metrics crate needs to be bumped to fix ahash compilation failure on Rust Nightly

### ISSUE THREAD

**Issue by fitzthum** [importcjj/mobc#90]
See [issue in ahash](https://github.com/tkaitchuck/aHash/issues/200) and [fix in metrics](https://github.com/metrics-rs/metrics/commit/f7e979a1b648e0dd8b25ff179c11ce5e15727fcc) that is not picked up here.

**Comment by janeisklar** [comment]
Since the fix has been merged, do you have an ETA when there will be a new release that includes it? No pressure, just trying to figure out what to do with our failing CI:)

**Comment by garrensmith** [comment]
@janeisklar thanks for the reminder. New release is published https://github.com/importcjj/mobc/pull/94
